const SET_SHOP_DATA = "SET_SHOP_DATA",
  SET_CLOSE = "SET_CLOSE",
  SET_ACTIVE_STORE = "SET_ACTIVE_STORE",
  SET_ACTIVE_ITEM = "SET_ACTIVE_ITEM",
  SET_SHOP_ITEM = "SET_SHOP_ITEM",
  SET_ORDER = "SET_ORDER",
  SET_DETAIL_CARD = "SET_DETAIL_CARD",
  SET_DETAIL_ACTIVE_NAV = "SET_DETAIL_ACTIVE_NAV";

export {
  SET_SHOP_DATA,
  SET_CLOSE,
  SET_ACTIVE_STORE,
  SET_ACTIVE_ITEM,
  SET_SHOP_ITEM,
  SET_ORDER,
  SET_DETAIL_CARD,
  SET_DETAIL_ACTIVE_NAV,
};
